version: "3.8"

services:
  agentlab:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME="sitewiz-videos"
